import "./globals.css";
import Navbar from "@/Components/Navbar";
import { Inter } from "next/font/google"; 

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: "to do app",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}> {}
        <Navbar />
        {children}
      </body>
    </html>
  );
}
